apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  namespace: default
  labels:
    run: app
  name: app
spec:
  containers:
  - image: nginx
    name: app2
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
